package studentplanner;


import java.awt.CardLayout;
import java.util.ArrayList;

public class DashboardGUI extends javax.swing.JFrame {


    public DashboardGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        GUI = new javax.swing.JPanel();
        DashboardGUI = new javax.swing.JPanel();
        dashboardLabel = new javax.swing.JLabel();
        moduleButton = new javax.swing.JButton();
        milestoneButton = new javax.swing.JButton();
        gradePlannerButton = new javax.swing.JButton();
        MilestoneGUI = new javax.swing.JPanel();
        milestoneLabel = new javax.swing.JLabel();
        GradePlannerGUI = new javax.swing.JPanel();
        gradePlannerLabel = new javax.swing.JLabel();
        ModuleGUI = new javax.swing.JPanel();
        assessmentButton = new javax.swing.JButton();
        moduleLabel = new javax.swing.JLabel();
        gradePlannerButton1 = new javax.swing.JButton();
        AssessmentGUI = new javax.swing.JPanel();
        taskButton = new javax.swing.JButton();
        assessmentLabel = new javax.swing.JLabel();
        TaskGUI = new javax.swing.JPanel();
        activityButton = new javax.swing.JButton();
        taskLabel = new javax.swing.JLabel();
        taskNameTextField = new javax.swing.JTextField();
        taskDescriptionTextField = new javax.swing.JTextField();
        jProgressBar1 = new javax.swing.JProgressBar();
        taskAssessmentTextField = new javax.swing.JTextField();
        taskWeightTextField = new javax.swing.JTextField();
        taskNameLabel = new javax.swing.JLabel();
        taskDescriptionLabel = new javax.swing.JLabel();
        taskAssessmentLabel = new javax.swing.JLabel();
        taskWeightLabel = new javax.swing.JLabel();
        taskProgressLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        activitiesTable = new javax.swing.JTable();
        titleLabel1 = new javax.swing.JLabel();
        ActivityGUI = new javax.swing.JPanel();
        activityLabel = new javax.swing.JLabel();
        viewDashboardButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        GUI.setLayout(new java.awt.CardLayout());

        dashboardLabel.setText("Dashboard");

        moduleButton.setText("Module View");
        moduleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moduleButtonActionPerformed(evt);
            }
        });

        milestoneButton.setText("Milestone View");
        milestoneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                milestoneButtonActionPerformed(evt);
            }
        });

        gradePlannerButton.setText("Grade Planner View");
        gradePlannerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradePlannerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DashboardGUILayout = new javax.swing.GroupLayout(DashboardGUI);
        DashboardGUI.setLayout(DashboardGUILayout);
        DashboardGUILayout.setHorizontalGroup(
            DashboardGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashboardGUILayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DashboardGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dashboardLabel)
                    .addComponent(gradePlannerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(milestoneButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(moduleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(469, Short.MAX_VALUE))
        );
        DashboardGUILayout.setVerticalGroup(
            DashboardGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashboardGUILayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dashboardLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(moduleButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(milestoneButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gradePlannerButton)
                .addContainerGap(278, Short.MAX_VALUE))
        );

        GUI.add(DashboardGUI, "dashboardCard");

        milestoneLabel.setText("Milestone");

        javax.swing.GroupLayout MilestoneGUILayout = new javax.swing.GroupLayout(MilestoneGUI);
        MilestoneGUI.setLayout(MilestoneGUILayout);
        MilestoneGUILayout.setHorizontalGroup(
            MilestoneGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MilestoneGUILayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(milestoneLabel)
                .addContainerGap(571, Short.MAX_VALUE))
        );
        MilestoneGUILayout.setVerticalGroup(
            MilestoneGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MilestoneGUILayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(milestoneLabel)
                .addContainerGap(383, Short.MAX_VALUE))
        );

        GUI.add(MilestoneGUI, "milestoneCard");

        gradePlannerLabel.setText("Grade Planner");

        javax.swing.GroupLayout GradePlannerGUILayout = new javax.swing.GroupLayout(GradePlannerGUI);
        GradePlannerGUI.setLayout(GradePlannerGUILayout);
        GradePlannerGUILayout.setHorizontalGroup(
            GradePlannerGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GradePlannerGUILayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gradePlannerLabel)
                .addContainerGap(546, Short.MAX_VALUE))
        );
        GradePlannerGUILayout.setVerticalGroup(
            GradePlannerGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GradePlannerGUILayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gradePlannerLabel)
                .addContainerGap(383, Short.MAX_VALUE))
        );

        GUI.add(GradePlannerGUI, "gradePlannerCard");

        assessmentButton.setText("Assessment View");
        assessmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assessmentButtonActionPerformed(evt);
            }
        });

        moduleLabel.setText("Module");

        gradePlannerButton1.setText("Grade Planner View");
        gradePlannerButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradePlannerButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ModuleGUILayout = new javax.swing.GroupLayout(ModuleGUI);
        ModuleGUI.setLayout(ModuleGUILayout);
        ModuleGUILayout.setHorizontalGroup(
            ModuleGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModuleGUILayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ModuleGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(moduleLabel)
                    .addComponent(gradePlannerButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(assessmentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(480, Short.MAX_VALUE))
        );
        ModuleGUILayout.setVerticalGroup(
            ModuleGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModuleGUILayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(moduleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(assessmentButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gradePlannerButton1)
                .addContainerGap(313, Short.MAX_VALUE))
        );

        GUI.add(ModuleGUI, "moduleCard");

        taskButton.setText("Task View");
        taskButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taskButtonActionPerformed(evt);
            }
        });

        assessmentLabel.setText("Assessment");

        javax.swing.GroupLayout AssessmentGUILayout = new javax.swing.GroupLayout(AssessmentGUI);
        AssessmentGUI.setLayout(AssessmentGUILayout);
        AssessmentGUILayout.setHorizontalGroup(
            AssessmentGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AssessmentGUILayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AssessmentGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(assessmentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taskButton))
                .addContainerGap(525, Short.MAX_VALUE))
        );
        AssessmentGUILayout.setVerticalGroup(
            AssessmentGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AssessmentGUILayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(assessmentLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(taskButton)
                .addGap(0, 348, Short.MAX_VALUE))
        );

        GUI.add(AssessmentGUI, "assessmentCard");

        activityButton.setText("Activity View");
        activityButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activityButtonActionPerformed(evt);
            }
        });

        taskLabel.setText("Task");

        taskNameLabel.setText("Task Name:");

        taskDescriptionLabel.setText("Description:");

        taskAssessmentLabel.setText("Parent Assessment:");

        taskWeightLabel.setText("Weighting:");

        taskProgressLabel.setText("Progress:");

        titleLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Activities");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, TaskGUI, org.jdesktop.beansbinding.ObjectProperty.create(), activitiesTable, org.jdesktop.beansbinding.BeanProperty.create("elements"));
        bindingGroup.addBinding(binding);
        binding.bind();
        jScrollPane4.setViewportView(activitiesTable);

        titleLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        titleLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel1.setText("Task");

        javax.swing.GroupLayout TaskGUILayout = new javax.swing.GroupLayout(TaskGUI);
        TaskGUI.setLayout(TaskGUILayout);
        TaskGUILayout.setHorizontalGroup(
            TaskGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TaskGUILayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TaskGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TaskGUILayout.createSequentialGroup()
                        .addGroup(TaskGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(taskLabel)
                            .addComponent(activityButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TaskGUILayout.createSequentialGroup()
                        .addGap(0, 144, Short.MAX_VALUE)
                        .addGroup(TaskGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(TaskGUILayout.createSequentialGroup()
                                .addGroup(TaskGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(taskNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(taskDescriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(taskWeightLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(taskAssessmentLabel)
                                    .addComponent(taskProgressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)
                                .addGroup(TaskGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(taskNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(taskAssessmentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(taskDescriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(taskWeightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(105, 105, 105))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TaskGUILayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(251, 251, 251))
            .addGroup(TaskGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TaskGUILayout.createSequentialGroup()
                    .addContainerGap(260, Short.MAX_VALUE)
                    .addComponent(titleLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(254, 254, 254)))
        );
        TaskGUILayout.setVerticalGroup(
            TaskGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TaskGUILayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(taskLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(activityButton)
                .addGap(18, 18, 18)
                .addGroup(TaskGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(taskNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taskNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(TaskGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(taskDescriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taskDescriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(TaskGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(taskAssessmentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taskAssessmentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(TaskGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(taskWeightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taskWeightLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(TaskGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taskProgressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
            .addGroup(TaskGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(TaskGUILayout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(titleLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(363, 363, 363)))
        );

        GUI.add(TaskGUI, "taskCard");

        activityLabel.setText("Activity");

        javax.swing.GroupLayout ActivityGUILayout = new javax.swing.GroupLayout(ActivityGUI);
        ActivityGUI.setLayout(ActivityGUILayout);
        ActivityGUILayout.setHorizontalGroup(
            ActivityGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ActivityGUILayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(activityLabel)
                .addContainerGap(584, Short.MAX_VALUE))
        );
        ActivityGUILayout.setVerticalGroup(
            ActivityGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ActivityGUILayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(activityLabel)
                .addContainerGap(383, Short.MAX_VALUE))
        );

        GUI.add(ActivityGUI, "activityCard");

        viewDashboardButton.setText("Go to Dashboard");
        viewDashboardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDashboardButtonActionPerformed(evt);
            }
        });

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(viewDashboardButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(GUI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(GUI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewDashboardButton)
                    .addComponent(backButton))
                .addGap(19, 19, 19))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private int backIndex = -1;
    ArrayList<String> backList = new ArrayList<>();
    
    private void viewDashboardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDashboardButtonActionPerformed
        CardLayout card = (CardLayout)GUI.getLayout();
        card.show(GUI, "dashboardCard");        
        backList.add("dashboardCard");
        backIndex++;
    }//GEN-LAST:event_viewDashboardButtonActionPerformed

    private void moduleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moduleButtonActionPerformed
        CardLayout card = (CardLayout)GUI.getLayout();
        card.show(GUI, "moduleCard");        
        backList.add("dashboardCard");
        backIndex++;
    }//GEN-LAST:event_moduleButtonActionPerformed

    private void taskButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taskButtonActionPerformed
        CardLayout card = (CardLayout)GUI.getLayout();
        card.show(GUI, "taskCard");        
        backList.add("assessmentCard");
        backIndex++;
    }//GEN-LAST:event_taskButtonActionPerformed

    private void assessmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assessmentButtonActionPerformed
        CardLayout card = (CardLayout)GUI.getLayout();
        card.show(GUI, "assessmentCard");        
        backList.add("moduleCard");
        backIndex++;
    }//GEN-LAST:event_assessmentButtonActionPerformed

    private void activityButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activityButtonActionPerformed
        CardLayout card = (CardLayout)GUI.getLayout();
        card.show(GUI, "activityCard");        
        backList.add("taskCard");
        backIndex++;
    }//GEN-LAST:event_activityButtonActionPerformed

    private void milestoneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_milestoneButtonActionPerformed
        CardLayout card = (CardLayout)GUI.getLayout();
        card.show(GUI, "milestoneCard");        
        backList.add("dashboardCard");
        backIndex++;
    }//GEN-LAST:event_milestoneButtonActionPerformed

    private void gradePlannerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradePlannerButtonActionPerformed
        CardLayout card = (CardLayout)GUI.getLayout();
        card.show(GUI, "gradePlannerCard");        
        backList.add("dashboardCard");
        backIndex++;
    }//GEN-LAST:event_gradePlannerButtonActionPerformed

    private void gradePlannerButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradePlannerButton1ActionPerformed
        CardLayout card = (CardLayout)GUI.getLayout();
        card.show(GUI, "gradePlannerCard");        
        backList.add("moduleCard");
        backIndex++;
    }//GEN-LAST:event_gradePlannerButton1ActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        if(backIndex > -1){
            CardLayout card = (CardLayout)GUI.getLayout();
            card.show(GUI, backList.get(backIndex));
            backList.remove(backIndex);
            backIndex--;
        }
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ActivityGUI;
    private javax.swing.JPanel AssessmentGUI;
    private javax.swing.JPanel DashboardGUI;
    private javax.swing.JPanel GUI;
    private javax.swing.JPanel GradePlannerGUI;
    private javax.swing.JPanel MilestoneGUI;
    private javax.swing.JPanel ModuleGUI;
    private javax.swing.JPanel TaskGUI;
    private javax.swing.JTable activitiesTable;
    private javax.swing.JButton activityButton;
    private javax.swing.JLabel activityLabel;
    private javax.swing.JButton assessmentButton;
    private javax.swing.JLabel assessmentLabel;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel dashboardLabel;
    private javax.swing.JButton gradePlannerButton;
    private javax.swing.JButton gradePlannerButton1;
    private javax.swing.JLabel gradePlannerLabel;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton milestoneButton;
    private javax.swing.JLabel milestoneLabel;
    private javax.swing.JButton moduleButton;
    private javax.swing.JLabel moduleLabel;
    private javax.swing.JLabel taskAssessmentLabel;
    private javax.swing.JTextField taskAssessmentTextField;
    private javax.swing.JButton taskButton;
    private javax.swing.JLabel taskDescriptionLabel;
    private javax.swing.JTextField taskDescriptionTextField;
    private javax.swing.JLabel taskLabel;
    private javax.swing.JLabel taskNameLabel;
    private javax.swing.JTextField taskNameTextField;
    private javax.swing.JLabel taskProgressLabel;
    private javax.swing.JLabel taskWeightLabel;
    private javax.swing.JTextField taskWeightTextField;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel titleLabel1;
    private javax.swing.JButton viewDashboardButton;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
