package studentplanner;


import java.awt.CardLayout;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author natha
 */
public class DashboardGUI extends javax.swing.JFrame {

    /**
     * Creates new form DashboardGUI
     */
    public DashboardGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GUI = new javax.swing.JPanel();
        DashboardGUI = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        moduleButton = new javax.swing.JButton();
        ModuleGUI = new javax.swing.JPanel();
        assessmentButton = new javax.swing.JButton();
        moduleLabel = new javax.swing.JLabel();
        AssessmentGUI = new javax.swing.JPanel();
        taskButton = new javax.swing.JButton();
        assessmentLabel = new javax.swing.JLabel();
        TaskGUI = new javax.swing.JPanel();
        activityButton = new javax.swing.JButton();
        taskLabel = new javax.swing.JLabel();
        ActivityGUI = new javax.swing.JPanel();
        activityLabel = new javax.swing.JLabel();
        viewDashboardButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        GUI.setLayout(new java.awt.CardLayout());

        jLabel1.setText("Dashboard");

        moduleButton.setText("Module View");
        moduleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moduleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DashboardGUILayout = new javax.swing.GroupLayout(DashboardGUI);
        DashboardGUI.setLayout(DashboardGUILayout);
        DashboardGUILayout.setHorizontalGroup(
            DashboardGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashboardGUILayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DashboardGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(moduleButton))
                .addContainerGap(509, Short.MAX_VALUE))
        );
        DashboardGUILayout.setVerticalGroup(
            DashboardGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashboardGUILayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(moduleButton)
                .addContainerGap(337, Short.MAX_VALUE))
        );

        GUI.add(DashboardGUI, "card3");

        assessmentButton.setText("Assessment View");
        assessmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assessmentButtonActionPerformed(evt);
            }
        });

        moduleLabel.setText("Module");

        javax.swing.GroupLayout ModuleGUILayout = new javax.swing.GroupLayout(ModuleGUI);
        ModuleGUI.setLayout(ModuleGUILayout);
        ModuleGUILayout.setHorizontalGroup(
            ModuleGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModuleGUILayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ModuleGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(moduleLabel)
                    .addComponent(assessmentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(492, Short.MAX_VALUE))
        );
        ModuleGUILayout.setVerticalGroup(
            ModuleGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModuleGUILayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(moduleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(assessmentButton)
                .addContainerGap(336, Short.MAX_VALUE))
        );

        GUI.add(ModuleGUI, "card2");

        taskButton.setText("Task View");
        taskButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taskButtonActionPerformed(evt);
            }
        });

        assessmentLabel.setText("Assessment");

        javax.swing.GroupLayout AssessmentGUILayout = new javax.swing.GroupLayout(AssessmentGUI);
        AssessmentGUI.setLayout(AssessmentGUILayout);
        AssessmentGUILayout.setHorizontalGroup(
            AssessmentGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AssessmentGUILayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AssessmentGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(assessmentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taskButton))
                .addContainerGap(525, Short.MAX_VALUE))
        );
        AssessmentGUILayout.setVerticalGroup(
            AssessmentGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AssessmentGUILayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(assessmentLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(taskButton)
                .addGap(0, 337, Short.MAX_VALUE))
        );

        GUI.add(AssessmentGUI, "card4");

        activityButton.setText("Activity View");
        activityButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activityButtonActionPerformed(evt);
            }
        });

        taskLabel.setText("Task");

        javax.swing.GroupLayout TaskGUILayout = new javax.swing.GroupLayout(TaskGUI);
        TaskGUI.setLayout(TaskGUILayout);
        TaskGUILayout.setHorizontalGroup(
            TaskGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TaskGUILayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TaskGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(taskLabel)
                    .addComponent(activityButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(478, Short.MAX_VALUE))
        );
        TaskGUILayout.setVerticalGroup(
            TaskGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TaskGUILayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(taskLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(activityButton)
                .addGap(0, 348, Short.MAX_VALUE))
        );

        GUI.add(TaskGUI, "card5");

        activityLabel.setText("Activity");

        javax.swing.GroupLayout ActivityGUILayout = new javax.swing.GroupLayout(ActivityGUI);
        ActivityGUI.setLayout(ActivityGUILayout);
        ActivityGUILayout.setHorizontalGroup(
            ActivityGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ActivityGUILayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(activityLabel)
                .addContainerGap(557, Short.MAX_VALUE))
        );
        ActivityGUILayout.setVerticalGroup(
            ActivityGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ActivityGUILayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(activityLabel)
                .addContainerGap(383, Short.MAX_VALUE))
        );

        GUI.add(ActivityGUI, "card6");

        viewDashboardButton.setText("Go to Dashboard");
        viewDashboardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDashboardButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(viewDashboardButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(GUI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(GUI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewDashboardButton)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewDashboardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDashboardButtonActionPerformed
   
        CardLayout card = (CardLayout)GUI.getLayout();
        card.show(GUI, "card3");
    }//GEN-LAST:event_viewDashboardButtonActionPerformed

    private void moduleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moduleButtonActionPerformed
        CardLayout card = (CardLayout)GUI.getLayout();
        card.show(GUI, "card2");
    }//GEN-LAST:event_moduleButtonActionPerformed

    private void taskButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taskButtonActionPerformed
        CardLayout card = (CardLayout)GUI.getLayout();
        card.show(GUI, "card5");
    }//GEN-LAST:event_taskButtonActionPerformed

    private void assessmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assessmentButtonActionPerformed
        CardLayout card = (CardLayout)GUI.getLayout();
        card.show(GUI, "card4");
    }//GEN-LAST:event_assessmentButtonActionPerformed

    private void activityButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activityButtonActionPerformed
        CardLayout card = (CardLayout)GUI.getLayout();
        card.show(GUI, "card6");
    }//GEN-LAST:event_activityButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ActivityGUI;
    private javax.swing.JPanel AssessmentGUI;
    private javax.swing.JPanel DashboardGUI;
    private javax.swing.JPanel GUI;
    private javax.swing.JPanel ModuleGUI;
    private javax.swing.JPanel TaskGUI;
    private javax.swing.JButton activityButton;
    private javax.swing.JLabel activityLabel;
    private javax.swing.JButton assessmentButton;
    private javax.swing.JLabel assessmentLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton moduleButton;
    private javax.swing.JLabel moduleLabel;
    private javax.swing.JButton taskButton;
    private javax.swing.JLabel taskLabel;
    private javax.swing.JButton viewDashboardButton;
    // End of variables declaration//GEN-END:variables
}
